<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>R for Actuarial Statistics - 5&nbsp; Linear Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./references.html" rel="next">
<link href="./Chapter 3.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="custom.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Linear Regression.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Linear Regression</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">R for Actuarial Statistics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Setting Up Your R Environment</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Working with Variables.</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Chapter 3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Basic Data Types and Data Structures in R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Linear Regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction-to-linear-regression" id="toc-introduction-to-linear-regression" class="nav-link active" data-scroll-target="#introduction-to-linear-regression"><span class="header-section-number">5.0.1</span> <strong>Introduction to Linear Regression</strong></a></li>
  <li><a href="#fitting-linear-regression-in-r" id="toc-fitting-linear-regression-in-r" class="nav-link" data-scroll-target="#fitting-linear-regression-in-r"><span class="header-section-number">5.0.2</span> Fitting Linear Regression in R</a></li>
  <li><a href="#fitting-a-multiple-linear-regression-model-with-log-transformed-variables" id="toc-fitting-a-multiple-linear-regression-model-with-log-transformed-variables" class="nav-link" data-scroll-target="#fitting-a-multiple-linear-regression-model-with-log-transformed-variables"><span class="header-section-number">5.0.3</span> <strong>Fitting a Multiple Linear Regression Model with Log-Transformed Variables</strong></a></li>
  <li><a href="#using-categorical-variables-in-linear-regression" id="toc-using-categorical-variables-in-linear-regression" class="nav-link" data-scroll-target="#using-categorical-variables-in-linear-regression"><span class="header-section-number">5.0.4</span> <strong>Using Categorical Variables in Linear Regression</strong></a></li>
  <li><a href="#categorical-variables-with-interaction-terms-in-linear-regression" id="toc-categorical-variables-with-interaction-terms-in-linear-regression" class="nav-link" data-scroll-target="#categorical-variables-with-interaction-terms-in-linear-regression"><span class="header-section-number">5.0.5</span> <strong>Categorical Variables with Interaction Terms in Linear Regression</strong></a></li>
  <li><a href="#using-interaction-terms-in-regression" id="toc-using-interaction-terms-in-regression" class="nav-link" data-scroll-target="#using-interaction-terms-in-regression"><span class="header-section-number">5.0.6</span> <strong>Using Interaction Terms in Regression</strong></a></li>
  <li><a href="#interpretation-of-coefficients-with-interaction-terms" id="toc-interpretation-of-coefficients-with-interaction-terms" class="nav-link" data-scroll-target="#interpretation-of-coefficients-with-interaction-terms"><span class="header-section-number">5.0.7</span> <strong>Interpretation of Coefficients with Interaction Terms</strong></a></li>
  <li><a href="#generating-diagnostic-plots-in-r" id="toc-generating-diagnostic-plots-in-r" class="nav-link" data-scroll-target="#generating-diagnostic-plots-in-r"><span class="header-section-number">5.0.8</span> <strong>Generating Diagnostic Plots in R</strong></a></li>
  <li><a href="#predicting-values-in-r-with-linear-regression" id="toc-predicting-values-in-r-with-linear-regression" class="nav-link" data-scroll-target="#predicting-values-in-r-with-linear-regression"><span class="header-section-number">5.0.9</span> <strong>Predicting Values in R with Linear Regression</strong></a></li>
  <li><a href="#plotting-regression-line-for-simple-linear-regression-in-base-r" id="toc-plotting-regression-line-for-simple-linear-regression-in-base-r" class="nav-link" data-scroll-target="#plotting-regression-line-for-simple-linear-regression-in-base-r"><span class="header-section-number">5.0.10</span> <strong>Plotting Regression Line for Simple Linear Regression in Base R</strong></a></li>
  <li><a href="#optimizing-regression-models-forward-and-backward-selection-techniques" id="toc-optimizing-regression-models-forward-and-backward-selection-techniques" class="nav-link" data-scroll-target="#optimizing-regression-models-forward-and-backward-selection-techniques"><span class="header-section-number">5.0.11</span> <strong>Optimizing Regression Models: Forward and Backward Selection Techniques</strong></a></li>
  <li><a href="#forward-selection" id="toc-forward-selection" class="nav-link" data-scroll-target="#forward-selection"><span class="header-section-number">5.0.12</span> <strong>Forward Selection</strong></a></li>
  <li><a href="#backward-selection" id="toc-backward-selection" class="nav-link" data-scroll-target="#backward-selection"><span class="header-section-number">5.0.13</span> <strong>Backward Selection</strong></a></li>
  <li><a href="#application-in-r" id="toc-application-in-r" class="nav-link" data-scroll-target="#application-in-r"><span class="header-section-number">5.0.14</span> <strong>Application in R</strong></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Linear Regression</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="introduction-to-linear-regression" class="level3" data-number="5.0.1">
<h3 data-number="5.0.1" class="anchored" data-anchor-id="introduction-to-linear-regression"><span class="header-section-number">5.0.1</span> <strong>Introduction to Linear Regression</strong></h3>
<p>Linear regression aims to create a model that predicts or explains the dependent variable based on independent variables. It’s called “linear” because the relationship between the variables is modeled as a straight line or a plane in a multi-dimensional space.</p>
<p>Linear regression is widely used in various fields, including finance, economics, biology, and engineering, to understand relationships and make forecasts. It can be used for simple predictions or as a building block for more complex models.</p>
<section id="the-linear-regression-equation" class="level4" data-number="5.0.1.1">
<h4 data-number="5.0.1.1" class="anchored" data-anchor-id="the-linear-regression-equation"><span class="header-section-number">5.0.1.1</span> <strong>The Linear Regression Equation</strong></h4>
<p>The linear regression equation represents the expected relationship between the dependent variable and the independent variables. In its simplest form, the linear regression equation is:</p>
<p><span class="math inline">\(y=\beta_0+\beta_1*x_1+\beta_2*x_2+ϵ\)</span></p>
<ul>
<li><p><span class="math inline">\(y\)</span> is the dependent variable (the variable being predicted or explained).</p></li>
<li><p>​ <span class="math inline">\(\beta_0\)</span>is the intercept (the value of <span class="math inline">\(y\)</span> when all <span class="math inline">\(x_k\)</span> values are zero).</p></li>
<li><p><span class="math inline">\(\beta_1,\beta_2,\beta_3,...,\beta_k\)</span>​ are the coefficients (representing the effect of each independent variable on <span class="math inline">\(y\)</span>).</p></li>
<li><p><span class="math inline">\(x_1,x_2,x_3,...,x_k\)</span>​ are the independent variables (the predictors).</p></li>
<li><p>𝜖 is the error term (representing the variability not explained by the model).</p></li>
</ul>
<p>The goal of linear regression is to find the values of <span class="math inline">\(\beta_1,\beta_2,\beta_3,...,\beta_k\)</span>​ that minimize the sum of squared errors, which is the difference between the predicted values and the actual values.</p>
</section>
<section id="assumptions-of-linear-regression" class="level4" data-number="5.0.1.2">
<h4 data-number="5.0.1.2" class="anchored" data-anchor-id="assumptions-of-linear-regression"><span class="header-section-number">5.0.1.2</span> <strong>Assumptions of Linear Regression</strong></h4>
<p>Linear regression relies on several key assumptions. Violations of these assumptions can affect the validity and reliability of the model. The primary assumptions are:</p>
<ul>
<li><p><strong>Linearity</strong>: The relationship between the dependent variable and each independent variable must be linear. If the relationship is non-linear, linear regression may not be appropriate.</p></li>
<li><p><strong>Independence</strong>: The observations must be independent of each other. This assumption is critical in cases where data may have a time-related structure or where observations could be correlated.</p></li>
<li><p><strong>Homoscedasticity</strong>: The variance of the errors must be constant across different values of the independent variables. Uneven variance can lead to inaccurate estimates and biased statistical tests.</p></li>
<li><p><strong>Normality of Errors</strong>: The residuals (errors) should be approximately normally distributed. This assumption is crucial for hypothesis testing and confidence intervals.</p></li>
<li><p><strong>No Multicollinearity</strong>: The independent variables should not be highly correlated with each other. High multicollinearity can lead to unstable estimates and make it difficult to interpret the model.</p></li>
</ul>
<p>These assumptions should be checked and validated to ensure the linear regression model’s robustness and reliability.</p>
</section>
</section>
<section id="fitting-linear-regression-in-r" class="level3" data-number="5.0.2">
<h3 data-number="5.0.2" class="anchored" data-anchor-id="fitting-linear-regression-in-r"><span class="header-section-number">5.0.2</span> Fitting Linear Regression in R</h3>
<p>To start with linear regression, you need to load the dataset into your R session. We’ll use the <strong><code>prestige</code></strong> dataset from the <strong><code>carData</code></strong> package, which contains information on various professions, including education, income, women, prestige, census, and type.</p>
<section id="loading-the-data" class="level4" data-number="5.0.2.1">
<h4 data-number="5.0.2.1" class="anchored" data-anchor-id="loading-the-data"><span class="header-section-number">5.0.2.1</span> <strong>Loading the Data</strong></h4>
<p>First, ensure that the <strong><code>carData</code></strong> package is installed and loaded, then load the <strong><code>prestige</code></strong> dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install and load the carData package if needed</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(car)) {</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">"car"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: car</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'car' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'carData' was built under R version 4.3.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(carData)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the Prestige dataset</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"Prestige"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="fitting-simple-linear-regression" class="level4" data-number="5.0.2.2">
<h4 data-number="5.0.2.2" class="anchored" data-anchor-id="fitting-simple-linear-regression"><span class="header-section-number">5.0.2.2</span> Fitting Simple Linear regression</h4>
<p>To create a simple linear regression model in R, you can use the <strong><code>lm()</code></strong> function, which stands for “linear model.” The basic structure of the function is as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit a simple linear regression model</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>reg1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(prestige <span class="sc">~</span> education, <span class="at">data =</span> Prestige)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In this example, <strong><code>prestige</code></strong> is the dependent variable, and <strong><code>education</code></strong> is the independent variable. The tilde <strong><code>~</code></strong> separates the dependent variable on the left from the independent variable(s) on the right. The <strong><code>data</code></strong> parameter specifies the dataset used for the model.</p>
<p>After fitting the model, you can use the <strong><code>summary()</code></strong> function to get detailed information about the linear regression model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get a summary of the linear regression model</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = prestige ~ education, data = Prestige)

Residuals:
     Min       1Q   Median       3Q      Max 
-26.0397  -6.5228   0.6611   6.7430  18.1636 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -10.732      3.677  -2.919  0.00434 ** 
education      5.361      0.332  16.148  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.103 on 100 degrees of freedom
Multiple R-squared:  0.7228,    Adjusted R-squared:   0.72 
F-statistic: 260.8 on 1 and 100 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>This command provides a comprehensive summary of the model, including coefficients, standard errors, t-values, and other statistics that help evaluate the model’s performance.</p>
</section>
<section id="understanding-the-model-summary" class="level4" data-number="5.0.2.3">
<h4 data-number="5.0.2.3" class="anchored" data-anchor-id="understanding-the-model-summary"><span class="header-section-number">5.0.2.3</span> <strong>Understanding the Model Summary</strong></h4>
<p>Here’s what the summary output contains and what each section means:</p>
<ul>
<li><p><strong>Call</strong>: This section shows the formula used to fit the model, confirming the variables and dataset.</p></li>
<li><p><strong>Coefficients</strong>:</p>
<ul>
<li><p><strong>(Intercept)</strong>: The estimated value of the dependent variable when the independent variable is zero.</p></li>
<li><p><strong>Education</strong>: The estimated change in the dependent variable for each one-unit increase in education. A positive coefficient indicates a positive relationship.</p></li>
</ul></li>
<li><p><strong>Standard Errors</strong>: These values represent the uncertainty or variability in the coefficient estimates. Smaller standard errors indicate more precise estimates.</p></li>
<li><p><strong>t-values and p-values</strong>:</p>
<ul>
<li><p><strong>t-values</strong>: Used to test the null hypothesis that the coefficient is zero. Higher absolute t-values suggest the coefficient is significant.</p></li>
<li><p><strong>p-values</strong>: Indicate the probability of observing the estimated coefficient if the null hypothesis is true. Smaller p-values (e.g., less than 0.05) suggest statistical significance.</p></li>
</ul></li>
<li><p><strong>Residual Standard Error</strong>: Represents the typical size of the residuals (differences between observed and predicted values). Lower values suggest a better fit.</p></li>
<li><p><strong>R-squared and Adjusted R-squared</strong>:</p>
<ul>
<li><p><strong>R-squared</strong>: Indicates the proportion of variance in the dependent variable explained by the independent variable(s). Higher R-squared values suggest a stronger relationship.</p></li>
<li><p><strong>Adjusted R-squared</strong>: Adjusted for the number of predictors, providing a more accurate measure of fit for models with multiple independent variables.</p></li>
</ul></li>
<li><p><strong>F-statistic and p-value</strong>: These values test the overall significance of the model. A significant p-value indicates that the model provides a statistically significant relationship.</p></li>
</ul>
<p>From the Above Summary Output:</p>
<ul>
<li><p>The intercept in approximately -10.732, indicating the expected prestige when education in zero</p></li>
<li><p>The coefficient for <code>education</code> is 5.361, indicating that for every additional unit of education, prestige increases by 5.361</p></li>
<li><p>The model has R-squared value of 0.7228, suggesting that 72% of the variance in prestige is explained by education.</p></li>
<li><p>The p-value for <code>education</code> is very low, indicating that the relationship is statistically significant.</p></li>
</ul>
</section>
</section>
<section id="fitting-a-multiple-linear-regression-model-with-log-transformed-variables" class="level3" data-number="5.0.3">
<h3 data-number="5.0.3" class="anchored" data-anchor-id="fitting-a-multiple-linear-regression-model-with-log-transformed-variables"><span class="header-section-number">5.0.3</span> <strong>Fitting a Multiple Linear Regression Model with Log-Transformed Variables</strong></h3>
<p>Multiple linear regression allows for more complex modeling by including multiple independent variables to predict a dependent variable. In this case, we fit a multiple linear regression model with <strong><code>prestige</code></strong> as the dependent variable, and <strong><code>education</code></strong>, a log transformation of <strong><code>income</code></strong>, and <strong><code>women</code></strong> as the independent variables.</p>
<p>The use of log transformations is common when the independent variable has a skewed distribution or when we want to model the relative change (such as percentages). Here’s the model definition and summary:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fitting the multiple linear regression with log-transformed income</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>reg2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(prestige <span class="sc">~</span> education <span class="sc">+</span> <span class="fu">log</span>(income) <span class="sc">+</span> women, <span class="at">data =</span> Prestige)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = prestige ~ education + log(income) + women, data = Prestige)

Residuals:
    Min      1Q  Median      3Q     Max 
-17.364  -4.429  -0.101   4.316  19.179 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -110.9658    14.8429  -7.476 3.27e-11 ***
education      3.7305     0.3544  10.527  &lt; 2e-16 ***
log(income)   13.4382     1.9138   7.022 2.90e-10 ***
women          0.0469     0.0299   1.568     0.12    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.093 on 98 degrees of freedom
Multiple R-squared:  0.8351,    Adjusted R-squared:   0.83 
F-statistic: 165.4 on 3 and 98 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<section id="interpreting-the-log-transformed-coefficient" class="level4" data-number="5.0.3.1">
<h4 data-number="5.0.3.1" class="anchored" data-anchor-id="interpreting-the-log-transformed-coefficient"><span class="header-section-number">5.0.3.1</span> <strong>Interpreting the Log-Transformed Coefficient</strong></h4>
<p>When we include a log-transformed variable in a regression model, the interpretation of its coefficient changes slightly. Instead of a linear increase for each unit, the coefficient represents the change in the dependent variable for a percentage change in the independent variable.</p>
<p>In the <strong><code>summary(reg2)</code></strong>, the coefficient for <strong><code>log(income)</code></strong> indicates how much <strong><code>prestige</code></strong> is expected to change for a percentage change in <strong><code>income</code></strong>. To interpret it, you can divide the coefficient by 100. For example, if the coefficient for <strong><code>log(income)</code></strong> is 13.4382, the interpretation becomes:</p>
<ul>
<li>A 1% increase in <strong><code>income</code></strong> leads to an expected increase of about 0.13 points in <strong><code>prestige</code></strong>.</li>
</ul>
</section>
<section id="handling-log-transformation-of-variables-with-zeros" class="level4" data-number="5.0.3.2">
<h4 data-number="5.0.3.2" class="anchored" data-anchor-id="handling-log-transformation-of-variables-with-zeros"><span class="header-section-number">5.0.3.2</span> <strong>Handling Log Transformation of Variables with Zeros</strong></h4>
<p>If a variable contains zero values, direct log transformation is not possible, as the logarithm of zero is undefined. To address this issue, a common practice is to add a small constant (like 1) to every observation before applying the log transformation. This ensures that all values are positive and can be transformed safely.</p>
</section>
</section>
<section id="using-categorical-variables-in-linear-regression" class="level3" data-number="5.0.4">
<h3 data-number="5.0.4" class="anchored" data-anchor-id="using-categorical-variables-in-linear-regression"><span class="header-section-number">5.0.4</span> <strong>Using Categorical Variables in Linear Regression</strong></h3>
<p>Categorical variables can play a significant role in linear regression models. This guide focuses on how to include categorical independent variables in linear regression. When the dependent variable is categorical, alternative methods like logistic regression or multinomial regression are more appropriate.</p>
<p>For this example, we consider the <strong><code>Prestige</code></strong> dataset and fit a linear regression model where <strong><code>prestige</code></strong> is the dependent variable, and the independent variables include <strong><code>education</code></strong>, a log transformation of <strong><code>income</code></strong>, and a categorical variable, <strong><code>type</code></strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit a regression with a categorical variable</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>reg3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(prestige <span class="sc">~</span> education <span class="sc">+</span> <span class="fu">log</span>(income) <span class="sc">+</span> type, <span class="at">data =</span> Prestige)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = prestige ~ education + log(income) + type, data = Prestige)

Residuals:
    Min      1Q  Median      3Q     Max 
-13.511  -3.746   1.011   4.356  18.438 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -81.2019    13.7431  -5.909 5.63e-08 ***
education     3.2845     0.6081   5.401 5.06e-07 ***
log(income)  10.4875     1.7167   6.109 2.31e-08 ***
typeprof      6.7509     3.6185   1.866   0.0652 .  
typewc       -1.4394     2.3780  -0.605   0.5465    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.637 on 93 degrees of freedom
  (4 observations deleted due to missingness)
Multiple R-squared:  0.8555,    Adjusted R-squared:  0.8493 
F-statistic: 137.6 on 4 and 93 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<section id="understanding-categorical-variables-in-regression" class="level4" data-number="5.0.4.1">
<h4 data-number="5.0.4.1" class="anchored" data-anchor-id="understanding-categorical-variables-in-regression"><span class="header-section-number">5.0.4.1</span> <strong>Understanding Categorical Variables in Regression</strong></h4>
<p>In this model, <strong><code>type</code></strong> is a categorical or factor variable with three levels: <strong><code>bc</code></strong> (blue collar), <strong><code>prof</code></strong> (professional, managerial, and technical), and <strong><code>wc</code></strong> (white collar). R automatically recognizes it as a factor and treats it accordingly. The missing level in the coefficient summary (<strong><code>wc</code></strong> in this case) is considered the baseline or reference group. This means the other levels are compared to this baseline. If you want to get the estimate for the baseline group, remember to add the intercept value.</p>
</section>
<section id="changing-the-reference-group" class="level4" data-number="5.0.4.2">
<h4 data-number="5.0.4.2" class="anchored" data-anchor-id="changing-the-reference-group"><span class="header-section-number">5.0.4.2</span> <strong>Changing the Reference Group</strong></h4>
<p>R automatically selects the first level as the reference group. If you want to change the reference group, you can manually reorder the factor levels.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Change the reference group to 'bc'</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>Prestige<span class="sc">$</span>type <span class="ot">&lt;-</span> <span class="fu">factor</span>(Prestige<span class="sc">$</span>type, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"bc"</span>, <span class="st">"wc"</span>, <span class="st">"prof"</span>))</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the regression model with the new reference group</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>reg3_reorder <span class="ot">&lt;-</span> <span class="fu">lm</span>(prestige <span class="sc">~</span> education <span class="sc">+</span> <span class="fu">log</span>(income) <span class="sc">+</span> type, <span class="at">data =</span> Prestige)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg3_reorder)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = prestige ~ education + log(income) + type, data = Prestige)

Residuals:
    Min      1Q  Median      3Q     Max 
-13.511  -3.746   1.011   4.356  18.438 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -81.2019    13.7431  -5.909 5.63e-08 ***
education     3.2845     0.6081   5.401 5.06e-07 ***
log(income)  10.4875     1.7167   6.109 2.31e-08 ***
typewc       -1.4394     2.3780  -0.605   0.5465    
typeprof      6.7509     3.6185   1.866   0.0652 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.637 on 93 degrees of freedom
  (4 observations deleted due to missingness)
Multiple R-squared:  0.8555,    Adjusted R-squared:  0.8493 
F-statistic: 137.6 on 4 and 93 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>By reordering the levels, you change the baseline reference group. In this example, the new reference group is <strong><code>bc</code></strong> (blue collar).</p>
</section>
<section id="showing-all-factor-levels" class="level4" data-number="5.0.4.3">
<h4 data-number="5.0.4.3" class="anchored" data-anchor-id="showing-all-factor-levels"><span class="header-section-number">5.0.4.3</span> <strong>Showing All Factor Levels</strong></h4>
<p>If you want to show all factor levels in the coefficient summary, including the baseline, you can remove the intercept in the model. This approach will display separate estimates for each factor level.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the regression model without intercept to show all factor levels</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>reg3_showall <span class="ot">&lt;-</span> <span class="fu">lm</span>(prestige <span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> education <span class="sc">+</span> <span class="fu">log</span>(income) <span class="sc">+</span> type, <span class="at">data =</span> Prestige)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg3_showall)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = prestige ~ 0 + education + log(income) + type, data = Prestige)

Residuals:
    Min      1Q  Median      3Q     Max 
-13.511  -3.746   1.011   4.356  18.438 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
education     3.2845     0.6081   5.401 5.06e-07 ***
log(income)  10.4875     1.7167   6.109 2.31e-08 ***
typebc      -81.2019    13.7431  -5.909 5.63e-08 ***
typewc      -82.6413    13.7875  -5.994 3.86e-08 ***
typeprof    -74.4510    15.1175  -4.925 3.65e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.637 on 93 degrees of freedom
  (4 observations deleted due to missingness)
Multiple R-squared:  0.9835,    Adjusted R-squared:  0.9826 
F-statistic:  1107 on 5 and 93 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>With this approach, all factor levels are displayed with their estimates, allowing you to see the effect of each level independently.</p>
</section>
</section>
<section id="categorical-variables-with-interaction-terms-in-linear-regression" class="level3" data-number="5.0.5">
<h3 data-number="5.0.5" class="anchored" data-anchor-id="categorical-variables-with-interaction-terms-in-linear-regression"><span class="header-section-number">5.0.5</span> <strong>Categorical Variables with Interaction Terms in Linear Regression</strong></h3>
<p>In linear regression, interaction terms allow us to study how the relationship between one independent variable and the dependent variable changes depending on the level of another independent variable. When working with categorical variables, interactions can reveal nuanced insights about the data.</p>
<p>Here is an example of a linear regression model with interaction terms using the <strong><code>Prestige</code></strong> dataset. The model examines how <strong><code>prestige</code></strong> is influenced by interactions between <strong><code>type</code></strong> (a categorical variable with levels <strong><code>bc</code></strong>, <strong><code>wc</code></strong>, and <strong><code>prof</code></strong>) and <strong><code>education</code></strong> as well as <strong><code>log(income)</code></strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit a regression model with interaction terms</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>reg4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(prestige <span class="sc">~</span> type <span class="sc">*</span> (education <span class="sc">+</span> <span class="fu">log</span>(income)), <span class="at">data =</span> Prestige)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Alternate ways to define the same interaction model</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>reg4a <span class="ot">&lt;-</span> <span class="fu">lm</span>(prestige <span class="sc">~</span> education <span class="sc">+</span> <span class="fu">log</span>(income) <span class="sc">+</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>              type <span class="sc">+</span> <span class="fu">log</span>(income)<span class="sc">:</span>type <span class="sc">+</span> education<span class="sc">:</span>type,</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> Prestige)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>reg4b <span class="ot">&lt;-</span> <span class="fu">lm</span>(prestige <span class="sc">~</span> education <span class="sc">*</span> type <span class="sc">+</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>              <span class="fu">log</span>(income) <span class="sc">*</span> type, <span class="at">data =</span> Prestige)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="using-interaction-terms-in-regression" class="level3" data-number="5.0.6">
<h3 data-number="5.0.6" class="anchored" data-anchor-id="using-interaction-terms-in-regression"><span class="header-section-number">5.0.6</span> <strong>Using Interaction Terms in Regression</strong></h3>
<p>Interaction terms can be defined using the <strong><code>*</code></strong> operator in the formula. In this example, <strong><code>type * (education + log(income))</code></strong> creates interaction terms between <strong><code>type</code></strong> and <strong><code>education</code></strong>, and <strong><code>type</code></strong> and <strong><code>log(income)</code></strong>. This can also be broken down into multiple explicit terms, as shown in <strong><code>reg4a</code></strong> and <strong><code>reg4b</code></strong>.</p>
</section>
<section id="interpretation-of-coefficients-with-interaction-terms" class="level3" data-number="5.0.7">
<h3 data-number="5.0.7" class="anchored" data-anchor-id="interpretation-of-coefficients-with-interaction-terms"><span class="header-section-number">5.0.7</span> <strong>Interpretation of Coefficients with Interaction Terms</strong></h3>
<p>To illustrate the interpretation of coefficients with interaction terms, consider the following table, which shows the coefficients for each variable across different levels of <strong><code>type</code></strong>:</p>
<table class="table">
<colgroup>
<col style="width: 17%">
<col style="width: 12%">
<col style="width: 35%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><strong>bc</strong></th>
<th><strong>wc</strong></th>
<th><strong>prof</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>-120.05</td>
<td>-120.05 + 30.24 = -89.81</td>
<td>-120.05 + 85.16 = -34.89</td>
</tr>
<tr class="even">
<td>log(income)</td>
<td>15.98</td>
<td>15.98 - 8.16 = 7.82</td>
<td>15.98 - 9.43 = 6.55</td>
</tr>
<tr class="odd">
<td>education</td>
<td>2.34</td>
<td>2.34 + 3.64 = 5.98</td>
<td>2.34 + 0.697 = 3.037</td>
</tr>
</tbody>
</table>
<p>This table highlights that:</p>
<ul>
<li><p>The intercept differs based on the level of <strong><code>type</code></strong>.</p></li>
<li><p>For <strong><code>bc</code></strong>, the intercept is -120.05, but for <strong><code>wc</code></strong> and <strong><code>prof</code></strong>, it is adjusted based on the interaction terms.</p></li>
<li><p>Similar adjustments occur for <strong><code>log(income)</code></strong> and <strong><code>education</code></strong>, showing the effect of the interaction term on these coefficients.</p></li>
</ul>
</section>
<section id="generating-diagnostic-plots-in-r" class="level3" data-number="5.0.8">
<h3 data-number="5.0.8" class="anchored" data-anchor-id="generating-diagnostic-plots-in-r"><span class="header-section-number">5.0.8</span> <strong>Generating Diagnostic Plots in R</strong></h3>
<p>To create diagnostic plots for a regression model, use the <strong><code>plot()</code></strong> function on your linear model object (<strong><code>lm</code></strong>). This will generate four key plots that help assess the assumptions of linear regression:</p>
<ol type="1">
<li><p><strong>Residuals vs.&nbsp;Fitted</strong>: Checks for non-linearity and heteroscedasticity.</p></li>
<li><p><strong>Normal Q-Q</strong>: Evaluates if the residuals follow a normal distribution.</p></li>
<li><p><strong>Scale-Location</strong>: Assesses homoscedasticity.</p></li>
<li><p><strong>Residuals vs.&nbsp;Leverage</strong>: Identifies influential points.</p></li>
</ol>
<p>To create these plots in a single output, you can use <strong><code>par(mfrow = c(2, 2))</code></strong> to arrange them in a 2x2 grid.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Assuming you have a linear regression model named 'reg'</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))  <span class="co"># Set the plot layout to 2x2</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(reg1)             <span class="co"># Generate the diagnostic plots</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Linear-Regression_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="interpreting-diagnostic-plots" class="level4" data-number="5.0.8.1">
<h4 data-number="5.0.8.1" class="anchored" data-anchor-id="interpreting-diagnostic-plots"><span class="header-section-number">5.0.8.1</span> <strong>Interpreting Diagnostic Plots</strong></h4>
<p>Now let’s go through each plot and describe what to look for, including potential issues and troubleshooting tips.</p>
<ol type="1">
<li><p><strong>Residuals vs.&nbsp;Fitted</strong></p>
<ul>
<li>This plot should ideally show no distinct pattern. A pattern or curve suggests non-linearity, indicating that a transformation or polynomial regression may be needed. If the spread of residuals widens or narrows as fitted values increase, it suggests heteroscedasticity, which can be addressed with robust standard errors or transformation.</li>
</ul></li>
<li><p><strong>Normal Q-Q</strong></p>
<ul>
<li>This plot helps check if residuals follow a normal distribution. If the points follow a straight line, residuals are approximately normal. Deviations from this line, especially at the ends, suggest non-normality, which could require transformation or using non-parametric models.</li>
</ul></li>
<li><p><strong>Scale-Location</strong></p>
<ul>
<li>This plot checks for homoscedasticity. A horizontal line with even spread of points suggests constant variance of residuals. If the points form a funnel or exhibit other patterns, it indicates heteroscedasticity.</li>
</ul></li>
<li><p><strong>Residuals vs.&nbsp;Leverage</strong></p>
<ul>
<li>This plot helps identify influential points. Points with high leverage (far from the x-axis) or large residuals could significantly affect the regression results. Consider removing outliers or using robust regression techniques if influential points are identified.</li>
</ul></li>
</ol>
</section>
</section>
<section id="predicting-values-in-r-with-linear-regression" class="level3" data-number="5.0.9">
<h3 data-number="5.0.9" class="anchored" data-anchor-id="predicting-values-in-r-with-linear-regression"><span class="header-section-number">5.0.9</span> <strong>Predicting Values in R with Linear Regression</strong></h3>
<p>The <strong><code>predict()</code></strong> function requires two key inputs: the fitted regression model and a data frame containing the new data points for which you want predictions.</p>
<p>First, let’s create a data frame with the values for which you want to predict <strong><code>prestige</code></strong>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a new data frame with education, log(income), and women values</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>new_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">education =</span> <span class="fu">c</span>(<span class="dv">12</span>, <span class="dv">14</span>),  <span class="co"># Example education values for two points</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">income =</span> <span class="fu">c</span>(<span class="dv">15000</span>, <span class="dv">25000</span>), <span class="co"># Example income values (before log transformation)</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">women =</span> <span class="fu">c</span>(<span class="dv">20</span>, <span class="dv">30</span>)         <span class="co"># Example women percentage values</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Log-transform the income column</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>new_data<span class="sc">$</span>log_income <span class="ot">=</span> <span class="fu">log</span>(new_data<span class="sc">$</span>income)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, use the <strong><code>predict()</code></strong> function with the fitted model <strong><code>reg2</code></strong> to get the predicted <strong><code>prestige</code></strong> values:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict prestige using the fitted model and new data</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(reg2, <span class="at">newdata =</span> new_data)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(predictions)  <span class="co"># Display predicted prestige values</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2 
63.95751 78.75207 </code></pre>
</div>
</div>
</section>
<section id="plotting-regression-line-for-simple-linear-regression-in-base-r" class="level3" data-number="5.0.10">
<h3 data-number="5.0.10" class="anchored" data-anchor-id="plotting-regression-line-for-simple-linear-regression-in-base-r"><span class="header-section-number">5.0.10</span> <strong>Plotting Regression Line for Simple Linear Regression in Base R</strong></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the simple linear regression model</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>reg1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(prestige <span class="sc">~</span> education, <span class="at">data =</span> Prestige)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a scatter plot with base R</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Prestige<span class="sc">$</span>education, Prestige<span class="sc">$</span>prestige, </span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Education"</span>, </span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Prestige"</span>, </span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Regression of Prestige on Education"</span>)</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Add the regression line</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(reg1, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)  <span class="co"># Add regression line with red color and thicker line</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Linear-Regression_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li><p><strong><code>plot()</code></strong> creates the scatter plot with axes labeled and a title.</p></li>
<li><p><strong><code>abline()</code></strong> with a linear model as an argument adds the regression line.</p></li>
</ul>
</section>
<section id="optimizing-regression-models-forward-and-backward-selection-techniques" class="level3" data-number="5.0.11">
<h3 data-number="5.0.11" class="anchored" data-anchor-id="optimizing-regression-models-forward-and-backward-selection-techniques"><span class="header-section-number">5.0.11</span> <strong>Optimizing Regression Models: Forward and Backward Selection Techniques</strong></h3>
</section>
<section id="forward-selection" class="level3" data-number="5.0.12">
<h3 data-number="5.0.12" class="anchored" data-anchor-id="forward-selection"><span class="header-section-number">5.0.12</span> <strong>Forward Selection</strong></h3>
<p>Forward selection starts with no predictors and adds them one at a time, selecting the variable that improves the model’s performance the most at each step. The process continues until adding new predictors does not significantly enhance the model.</p>
<section id="how-forward-selection-works" class="level4" data-number="5.0.12.1">
<h4 data-number="5.0.12.1" class="anchored" data-anchor-id="how-forward-selection-works"><span class="header-section-number">5.0.12.1</span> <strong>How Forward Selection Works</strong></h4>
<ol type="1">
<li><p><strong>Initial Model</strong>: Start with an intercept-only model.</p></li>
<li><p><strong>Variable Addition</strong>: Add the predictor that results in the greatest improvement in the model, usually evaluated using a criterion like AIC (Akaike Information Criterion), BIC (Bayesian Information Criterion), or adjusted R-squared.</p></li>
<li><p><strong>Iteration</strong>: Repeat step 2, adding one variable at a time, until no additional variables improve the model.</p></li>
</ol>
</section>
<section id="advantages-and-disadvantages-of-forward-selection" class="level4" data-number="5.0.12.2">
<h4 data-number="5.0.12.2" class="anchored" data-anchor-id="advantages-and-disadvantages-of-forward-selection"><span class="header-section-number">5.0.12.2</span> <strong>Advantages and Disadvantages of Forward Selection</strong></h4>
<ul>
<li><p><strong>Advantages</strong>:</p>
<ul>
<li><p>Relatively simple and computationally less expensive.</p></li>
<li><p>Can be useful when there are many potential predictors.</p></li>
</ul></li>
<li><p><strong>Disadvantages</strong>:</p>
<ul>
<li><p>May miss important interactions or nonlinear effects.</p></li>
<li><p>Can suffer from multicollinearity if variables are highly correlated.</p></li>
</ul></li>
</ul>
</section>
</section>
<section id="backward-selection" class="level3" data-number="5.0.13">
<h3 data-number="5.0.13" class="anchored" data-anchor-id="backward-selection"><span class="header-section-number">5.0.13</span> <strong>Backward Selection</strong></h3>
<p>Backward selection starts with a model that includes all potential predictors and removes them one at a time, dropping the variable that least improves the model at each step. The process continues until removing variables does not significantly affect the model.</p>
<section id="how-backward-selection-works" class="level4" data-number="5.0.13.1">
<h4 data-number="5.0.13.1" class="anchored" data-anchor-id="how-backward-selection-works"><span class="header-section-number">5.0.13.1</span> <strong>How Backward Selection Works</strong></h4>
<ol type="1">
<li><p><strong>Initial Model</strong>: Start with a model that includes all predictors.</p></li>
<li><p><strong>Variable Removal</strong>: Remove the predictor that has the least impact on the model, usually evaluated using a criterion like AIC, BIC, or adjusted R-squared.</p></li>
<li><p><strong>Iteration</strong>: Repeat step 2, removing one variable at a time, until further removal significantly worsens the model.</p></li>
</ol>
</section>
<section id="advantages-and-disadvantages-of-backward-selection" class="level4" data-number="5.0.13.2">
<h4 data-number="5.0.13.2" class="anchored" data-anchor-id="advantages-and-disadvantages-of-backward-selection"><span class="header-section-number">5.0.13.2</span> <strong>Advantages and Disadvantages of Backward Selection</strong></h4>
<ul>
<li><p><strong>Advantages</strong>:</p>
<ul>
<li><p>Can handle a large number of predictors and consider all of them.</p></li>
<li><p>May capture interactions or nonlinear effects better than forward selection.</p></li>
</ul></li>
<li><p><strong>Disadvantages</strong>:</p>
<ul>
<li><p>Requires more computation, especially with a large set of predictors.</p></li>
<li><p>Can be sensitive to multicollinearity.</p></li>
</ul></li>
</ul>
</section>
</section>
<section id="application-in-r" class="level3" data-number="5.0.14">
<h3 data-number="5.0.14" class="anchored" data-anchor-id="application-in-r"><span class="header-section-number">5.0.14</span> <strong>Application in R</strong></h3>
<p>To apply forward or backward selection in R, you can use the <strong><code>step()</code></strong> function, which performs both types of selection. Here’s an example of backward selection:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit a model with all predictors</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>full_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(prestige <span class="sc">~</span> education <span class="sc">+</span> <span class="fu">log</span>(income) <span class="sc">+</span> women, <span class="at">data =</span> Prestige)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform backward selection</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>backward_model <span class="ot">&lt;-</span> <span class="fu">step</span>(full_model, <span class="at">direction =</span> <span class="st">"backward"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=403.57
prestige ~ education + log(income) + women

              Df Sum of Sq     RSS    AIC
&lt;none&gt;                      4929.9 403.57
- women        1     123.8  5053.6 404.09
- log(income)  1    2480.4  7410.3 443.14
- education    1    5574.4 10504.3 478.73</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>backward_model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = prestige ~ education + log(income) + women, data = Prestige)

Coefficients:
(Intercept)    education  log(income)        women  
  -110.9658       3.7305      13.4382       0.0469  </code></pre>
</div>
</div>
<p>And an example of forward selection:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit an intercept-only model</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>null_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(prestige <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> Prestige)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform forward selection</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>forward_model <span class="ot">&lt;-</span> <span class="fu">step</span>(null_model, <span class="at">direction =</span> <span class="st">"forward"</span>, <span class="at">scope =</span> <span class="sc">~</span> education <span class="sc">+</span> <span class="fu">log</span>(income) <span class="sc">+</span> women)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=581.41
prestige ~ 1

              Df Sum of Sq   RSS    AIC
+ education    1   21608.4  8287 452.54
+ log(income)  1   16417.5 13478 502.15
&lt;none&gt;                     29895 581.41
+ women        1     418.6 29477 581.97

Step:  AIC=452.54
prestige ~ education

              Df Sum of Sq    RSS    AIC
+ log(income)  1    3233.4 5053.6 404.09
+ women        1     876.7 7410.3 443.14
&lt;none&gt;                     8287.0 452.54

Step:  AIC=404.09
prestige ~ education + log(income)

        Df Sum of Sq    RSS    AIC
+ women  1    123.75 4929.9 403.57
&lt;none&gt;               5053.6 404.09

Step:  AIC=403.57
prestige ~ education + log(income) + women</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>forward_model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = prestige ~ education + log(income) + women, data = Prestige)

Coefficients:
(Intercept)    education  log(income)        women  
  -110.9658       3.7305      13.4382       0.0469  </code></pre>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Chapter 3.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Basic Data Types and Data Structures in R</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./references.html" class="pagination-link">
        <span class="nav-page-text">References</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>